name: Build docker image and run unit tests

on:
  pull_request:
    types: [opened, synchronize, closed]
  push:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: fitapp:latest

    - name: Load .env.example file
      run: |
        cp .env.example .env

    - name: Build and run Docker container
      run: |
        docker-compose up -d

    - name: Run tests in docker container
      run: |
        chmod +x ./scripts/run_tests.sh
        ./scripts/run_tests.sh