name: Run Unit Tests

on:
  pull_request:
    types: [opened, synchronize, closed]
  push:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Grant execute permission to the script
      run: chmod +x scripts/run_tests.sh

    - name: Run Unit Tests
      run: |
        ./scripts/run_tests.sh